Table responsables {
    id int [pk, increment] // Primary key, auto-incremented
    Nombres varchar(50) // Name of the responsible person
    Apellidos varchar(50) // Name of the responsible person
    Correo varchar(100) // Email of the responsible person 
    Estado varchar(50) // Email of the responsible person 
}
 